name: nap-image-segmentation

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - opencv
  - matplotlib
  - onnxruntime
  - onnx
  - pytorch::pytorch-cuda=11.7
  - pandas
  - supervision
  - pre-commit

  - pip>=23
  - pip:
      - tensorflow
      - tensorflow-datasets
      - git+https://github.com/facebookresearch/segment-anything.git
