name: nap-image-segmentation

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - opencv
  - pip>=23
  - pip:
      - tensorflow
      - tensorflow-datasets
      - git+https://github.com/facebookresearch/segment-anything.git
      - black
      - supervision
      - numpy
      - pre-commit
      - torch==2.2.1+cu121
      - torchaudio==2.2.1+cu121
      - torchvision==0.17.1+cu121
