name: nap-image-segmentation

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pytorch::pytorch=2.2
  - pytorch::torchaudio=2.2
  - pytorch::torchvision=0.17
  - opencv
  - pre-commit
  - pip>=23
  - pip:
      - tensorflow
      - tensorflow-datasets
      - git+https://github.com/facebookresearch/segment-anything.git
      - black
      - supervision
      - numpy
      - pandas
      - matplotlib
